### ISSUE TITLE
Clarify marking "no issues on this page"

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/wellcome#20]
It isn't clear, at the moment, that pressing Finish without adding any tags is the same as marking no issues found for a page.

Possible solutions:

1. Add an explicit "Nothing here" button
2. Always show the current list of tags, defaulting to "No issues on this page."

**Comment by axgreen** [comment]
Minor tweak: can we add in the word "yet" to the "no issues on this page" label ("no issues on this page yet'")
