### ISSUE TITLE
Add a link to the blog to the top nav

### ISSUE THREAD

**Issue by axgreen** [zooniverse/wellcome#32]

**Comment by eatyourgreens** [comment]
Do we want to set up a new wordpress blog for this project (like blog.sciencegossip.org) or use an existing Wellcome blog?

**Comment by axgreen** [comment]
Good question - I'm not sure about this stuff. Will follow up with Sally and return with an answer

**Comment by axgreen** [comment]
As per Grant's email, he's setting up a blog for this project - so I guess it needs to link to that one.
