### ISSUE TITLE
Need to work out how to include descriptions of categories without pushing task and buttons right down the page

### ISSUE THREAD

**Issue by axgreen** [zooniverse/wellcome#36]

**Comment by axgreen** [comment]
Here's one idea - can descriptions move into a box above the task pane? (please excuse hasty drawing!)

![img_2872](https://cloud.githubusercontent.com/assets/13200172/11064340/991b7e4a-87b4-11e5-9888-06ba5bda3e0d.JPG)

**Comment by axgreen** [comment]
We also thought we could reduce the length of the descriptions:

Housing
Much of the information about housing in the reports is about the living conditions of London’s poor. The medical officers reported on overcrowded slums and the results of poor construction such as leaking sewers, poor ventilation and lack of sunlight due to closely packed houses. They recommended measures such as fumigation after infestations and cleaning after disease outbreaks.

Work
The medical officer inspected the health impact of London’s trades and industries. From reporting on the working conditions of homeworkers to the effects of tanneries and factories on their surroundings, they had the power to issue fines for breaking local by-laws and public health laws.

Food
The medical officer inspected all aspects of the city’s food supply, from food importers and manufacturers to abattoirs, from butchers and bakers shops to street vendors. He was particularly concerned with food adulteration – identifying hidden substances that shouldn’t be there – and incidents of food poisoning.

**Comment by eatyourgreens** [comment]
I'm experimenting with this layout in #37 It's deployed to the preview site, so you can take a look.

**Comment by axgreen** [comment]
I think that works well as a location - even with my 11" display you can see all the buttons before the fold. The only thing is that our background image is quite busy so the white text is a bit challenging to read. Maybe we should put some kind of semi transparent background to the text to improve legibility? Or I could modify the background image so it fades out at the top? What do you think?

**Comment by eatyourgreens** [comment]
Great: the current implementation was just a quick hack anyway, so I will work on something more robust and fix the background to make it more legible.

I'd say leave the background image as it is, otherwise you would find yourself trying to edit it to produce a version that works on tablet screens, laptops and desktop monitors.
