### ISSUE TITLE
Bug in IE 11.0.9600

### ISSUE THREAD

**Issue by axgreen** [zooniverse/wellcome#47]
![image](https://cloud.githubusercontent.com/assets/13200172/11564908/81c60a72-99d3-11e5-8dc7-edcab19b72ec.png)

When attempting to tag an issue, text blocks highlight but do not appear in the left panel (see screenshot). This prevents moving on beyond the first tag or successfully submitting an issue

**Comment by eatyourgreens** [comment]
Console error is `Unable to get property 'textContent' of undefined or null reference`

Weirdly, this works locally in IE11, but breaks on the staging site.
