### ISSUE TITLE
Add text to Profile page when not signed in and provide sign in dialog

### ISSUE THREAD

**Issue by Lalita17** [zooniverse/wellcome#58]
Text for Profile page before signing:
"Sign in to Profile to see the pages you've already tagged"

Username [username entry field]
Password [password entry field]
[sign in button and forgot password button]
[Sign up link]

**Comment by eatyourgreens** [comment]
zooniverse.org doesn't allow direct login from other domains, but we can hide the profile unless you are logged in to Zooniverse.

**Comment by Lalita17** [comment]
I think hiding the profile is a good idea in that case.
