### ISSUE TITLE
oauth host config + api host

### ISSUE THREAD

**Issue by camallen** [zooniverse/wellcome#69]
https://www.zooniverse.org/assets/doorkeeper/application-061546a8e4f74bd4cef78622f5069d98e812c649d729d074ebad1927901e877b.css

vs

https://panoptes.zooniverse.org/assets/doorkeeper/application-061546a8e4f74bd4cef78622f5069d98e812c649d729d074ebad1927901e877b.css

due to the way we run the api and UI code over the same domain via cloudfront the oauth server assets won't work *currently* via zooniverse.org/assets, etc

need to add an oauth host to `panoptes.zooniverse.org` [here](https://github.com/zooniverse/wellcome/blob/e160615ef1e9369c09a5cb0af0a9b7fe4601308a/app/panoptes/login-bar.cjsx#L11) but keep the api host the same to leverage the CDN.

**Comment by eatyourgreens** [comment]
Closed by #70
