### ISSUE TITLE
Link back to pages on the Wellcome site

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/wellcome#7]
Need to find out how to construct URLs for pages in the MOH reports.

**Comment by axgreen** [comment]
report page URLs are in the format wellcomelibrary.org/moh/report/**BNUMBER**#?asi=**VOLUMENUMBER**&ai=**IMAGENUMBER**

These numbers are all in the image filenames:

**BNUMBER** is the first part of the filename starting b... they're all b followed by 8 characters (nearly always digits, sometimes an 'x' at the end)

**VOLUMENUMBER** is the next part of the filename after the underscore. I think it will nearly always be 0, unless there are any reports with multiple volumes

**IMAGENUMBER** is the last part of the file name, it's a number corresponding to the order of the image in the book (sort of like the page number, except it includes all the blank pages etc)
